Add clang-format and workflow for consistency #21
fffelix-huang/Sonic pull request #22
Opened 2024-10-19 08:47 UTC by nikhiljangra264

#21 
1. Added clang-format rules to ensure consistency across source files.
1. Added a workflow test clang-format.yml to check code formatting on pull requests and when changes are made to the master branch.

2024-10-19 14:10 UTC, fffelix-huang commented
Thanks! I'll be reviewing within couple days.

2024-10-23 10:25 UTC, fffelix-huang requested changes
Hi

There are some small changes to be made.

2024-10-24 03:55 UTC, nikhiljangra264 commented on .clang-format
> +  AfterFunction: false
which one do you prefer?
1. value:false
```
namespace name {
class class_name {
   public:
    function_name() {
        if () {
        } else { 
        }
    }
}
}
```
2. value:true
```
namespace name 
{
class class_name 
{
   public:
    function_name() 
    {
        if () 
        {
        }
        else
        {
        }
    }
}
}
```

or combination

2024-10-25 07:22 UTC, nikhiljangra264 commented
Hello @fffelix-huang, I have made some changes requested

2024-10-25 07:22 UTC, nikhiljangra264 commented
apart from that I have added clang-format off and on at places like this
```cpp
// clang-format off
constexpr std::pair<Value, Value> PieceSquareTable[PieceType::PIECE_NB][Square::SQ_NB] = {
    { // Pawn
        {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0},
        {166, 256}, {192, 256}, {204, 256}, {216, 256}, {216, 256}, {204, 256}, {192, 256}, {166, 256},
        {166, 256}, {192, 256}, {210, 256}, {242, 256}, {242, 256}, {210, 256}, {192, 256}, {166, 256},
        {166, 256}, {192, 256}, {220, 256}, {268, 256}, {268, 256}, {220, 256}, {192, 256}, {166, 256},
        {166, 256}, {192, 256}, {220, 256}, {242, 256}, {242, 256}, {220, 256}, {192, 256}, {166, 256},
        {166, 256}, {192, 256}, {210, 256}, {216, 256}, {216, 256}, {210, 256}, {192, 256}, {166, 256},
        {166, 256}, {192, 256}, {204, 256}, {216, 256}, {216, 256}, {204, 256}, {192, 256}, {166, 256},
        {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0},
    },
}
```
to avoid formating on this code even if it exceeds the column width 100

2024-10-25 07:59 UTC, fffelix-huang commented
Great! This is better than I expected :)
One last request is to add formatting to Makefile, (`make format` should apply clang-format all source codes including cpps and hpps).
After this I'll merge this PR!

2024-10-25 10:38 UTC, nikhiljangra264 commented
I have Added it. so we can run the `make format` command to format code.
Please take a look

2024-10-25 10:44 UTC, merged